# Generated by Django 3.1.1 on 2020-10-03 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200923_0446'),
        ('shopping_cart', '0002_auto_20201002_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
